version: '3'

services:
  server:
    container_name: RESPONSIVE_BACKEND
    build: '.'
    volumes:
      - ./:/node-app/src
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9001:9001'

  db:
    image: postgres
    container_name: RESPONSIVE_DB
    environment:
      POSTGRES_PASSWORD: "pgadmin"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - pg-network

volumes:
  pgdata:

networks: 
  pg-network:
    driver: bridge