version: "3"

services:
  server:
    container_name: RESPONSIVE_BACKEND
    build: "."
    volumes:
      - ./:/node-app/build
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
      DB_PASSWORD: pgadmin
      DB_USER: pgadmin
      DB_NAME: responsive
      DB_HOST: db
      DB_PORT: 5432
      WAIT_HOSTS: db:5432
    depends_on:
      - db
    links:
      - db
    networks:
      - pg-network
    ports:
      - "9001:9001"

  db:
    image: postgres
    container_name: RESPONSIVE_DB
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: responsive
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: RESPONSIVE_PGADMIN
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - pg-network

volumes:
  pgdata:

networks:
  pg-network:
    driver: bridge
